'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:3001';
type Post={id:number;username:string;text:string;createdAt:string;likes:number;liked:boolean};
type Story={id:number;username:string;expiresAt:string};
export default function Home(){const [tab,setTab]=useState('home'),[posts,setPosts]=useState<Post[]>([]),[stories,setStories]=useState<Story[]>([]),[text,setText]=useState(''),[token,setToken]=useState(''),[auth,setAuth]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
async function load(){const [p,s]=await Promise.all([fetch(API+'/posts').then(r=>r.json()),fetch(API+'/stories').then(r=>r.json())]);setPosts(p);setStories(s)} useEffect(()=>{load()},[]);
async function login(){const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(d.accessToken){setToken(d.accessToken);setAuth(true)}else alert(d.message||'ورود ناموفق')}
async function publish(){if(!text.trim()||!token)return;await fetch(API+'/posts',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({text})});setText('');load()}
async function like(id:number){if(!token)return alert('ابتدا وارد حساب شوید');await fetch(API+'/posts/'+id+'/like',{method:'POST',headers:{Authorization:'Bearer '+token}});load()}
return <div className="shell"><aside><div className="brand">KD<span>GRAM</span></div>{['home','explore','messages','channels','profile'].map((x,i)=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{['🏠 خانه','🔎 کاوش','💬 پیام‌ها','📢 کانال‌ها','👤 پروفایل'][i]}</button>)}</aside><main><header><h1>{tab==='home'?'فید KDGRAM':tab==='messages'?'پیام‌ها':tab==='channels'?'کانال‌ها':tab==='profile'?'پروفایل':'کاوش'}</h1><span>Social × Messaging × More</span></header>{!auth&&<div className="card login"><b>ورود آزمایشی</b><input placeholder="ایمیل" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="رمز عبور" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={login}>ورود</button></div>}{tab==='home'&&<><div className="card stories">{stories.map(s=><div className="story" key={s.id}><div className="avatar">KD</div><small>{s.username}</small></div>)}<div className="story"><div className="avatar plus">＋</div><small>Story جدید</small></div></div><div className="card composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="چه خبر؟ یک پست بنویس..."/><button className="primary" onClick={publish}>انتشار</button></div>{posts.map(p=><article className="card post" key={p.id}><div className="posthead"><div className="avatar">{p.username.slice(0,2).toUpperCase()}</div><div><b>{p.username}</b><small>{new Date(p.createdAt).toLocaleString('fa-IR')}</small></div></div><p>{p.text}</p><div className="actions"><button onClick={()=>like(p.id)}>{p.liked?'♥':'♡'} {p.likes}</button><button>💬 دیدگاه</button><button>↗ اشتراک</button></div></article>)}</>}{tab==='explore'&&<div className="grid">{['#تکنولوژی','#سفر','#موسیقی','#ورزش','#عکاسی','#گیم'].map(x=><div className="tile" key={x}>{x}</div>)}</div>}{tab==='messages'&&<div className="card empty"><h2>💬 پیام‌رسان KDGRAM</h2><p>زیرساخت پیام‌رسانی Real-time آماده اتصال به WebSocket است.</p></div>}{tab==='channels'&&<div className="card empty"><h2>📢 کانال‌ها</h2><p>کانال‌های عمومی و خصوصی در معماری API تعریف شده‌اند.</p></div>}{tab==='profile'&&<div className="card profile"><div className="avatar big">KD</div><h2>KD User</h2><p>پروفایل شما</p></div>}</main></div>}
